---

- name: Create mountpoint
  ansible.builtin.file:
    state: directory
    path: "{{ atl_shared_mountpoint }}"
    mode: 0755
    owner: "{{ atl_product_user }}"
    group: "{{ atl_product_user }}"

- name: Enable mountpoint in fstab
  ansible.posix.mount:
    path: "{{ atl_shared_mountpoint }}"
    src: "{{ efs_target }}:{{ efs_src_dir }}"
    fstype: "{{ efs_type }}"
    opts: "{{ efs_mount_options }}"
    state: mounted
