---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-core"
    atl_product_user: "jira"
    # NOTE: This should be ignored because the version file exists (below).
    atl_product_version: "latest"

  pre_tasks:
    - name: Create cache dir
      ansible.builtin.file:
        path: '/media/atl/jira/shared/'
        state: directory
    - name: Seed version
      ansible.builtin.copy:
        dest: '/media/atl/jira/shared/jira-core.version'
        content: "7.9.0"
        force: false  # For idempotency check

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
