---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "confluence"
    atl_product_user: "confluence"
    atl_product_edition: "confluence"

    atl_jdbc_encoding: 'UTF-8'
    atl_jdbc_collation: 'UTF-8'

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_efs_config
    - role: product_common
    - role: product_install
    - role: database_init
    - role: confluence_common
    - role: confluence_config
    - role: product_startup
