---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"

    alt_product_home: "/media/atl/bitbucket"

    atl_use_system_jdk: true
    java_major_version: "11"
    atl_download_format: "tarball"

    atl_startup_systemd_params:
      - "UMask=0027"
      - "LimitNOFILE=4096"
      - "Environment=BITBUCKET_HOME=/media/atl/bitbucket"
      - "Environment=JAVA_HOME=/usr/lib/jvm/java"
      - "Environment=JVM_MAXIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_MINIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_SUPPORT_RECOMMENDED_ARGS={{ atl_jvm_opts }}"
    atl_startup_exec_options:
      - "--no-search"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
    - role: database_init
    - role: bitbucket_config
    - role: product_startup
    - role: bitbucket_dataset_restore
      when: atl_bitbucket_dataset_url is search ("(http|https)://")
