---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"

    atl_use_system_jdk: true
    java_major_version: "11" # BB 8 will drop JDK 8 support
    atl_download_format: "tarball"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
    - role: database_init
    - role: bitbucket_config
    - role: product_startup
    - role: bitbucket_dataset_restore
      when: atl_bitbucket_dataset_url is search ("(http|https)://")
