---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_product_user: "jira"
    atl_product_version: "7.13.2"

    # dbconfig.xml variables
    atl_jdbc_user: 'atljira'
    atl_jdbc_password: 'molecule_password'
    atl_jvm_heap: 'PLACEHOLDER'
    atl_jvm_opts: 'PLACEHOLDER'
    atl_cluster_node_id: 'FAKEID'
    atl_db_keepalive: 'false'
    atl_db_sockettimeout: '111'
    atl_db_poolminsize: 1111
    atl_db_poolmaxsize: 1111
    atl_db_minidle: 1111
    atl_db_maxidle: 1111
    atl_db_maxwaitmillis: 1111
    atl_db_minevictableidletimemillis: 1111
    atl_db_timebetweenevictionrunsmillis: 1111
    atl_db_removeabandoned: 'false'
    atl_db_removeabandonedtimeout: 1111
    atl_db_testwhileidle: 'false'
    atl_db_testonborrow: 'true'
    atl_db_engine: 'rds_postgres'

  pre_tasks:
    - name: Create shared home
      ansible.builtin.file:
        path: '/media/atl/jira/shared/'
        state: directory
    - name: Create jira-config.properties to check copy
      ansible.builtin.copy:
        dest: '/media/atl/jira/shared/jira-config.properties'
        content: "jira.projectkey.warning = testwarning"
        force: false  # For idempotency check

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
    - role: jira_config
