---

- name: Retrieve all available EC2 tags
  amazon.aws.ec2_tag_info:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
  register: ec2_instance_tags
  ignore_errors: true
  tags:
    - notest

- name: Retrieve autoscaling group
  ansible.builtin.set_fact:
    ec2_autoscaling_group: "{{ ec2_instance_tags.tags['aws:autoscaling:groupName'] | default('') }}"

- block:
    # No existing timestamp, so this is a first run. Persist some metadata into the ASG.
    - name: Fetch the git revision for this repo  # noqa: command-instead-of-module no-changed-when
      ansible.builtin.command:
        cmd: git rev-parse HEAD
      register: git_out

    - name: Setup the new ASG tags
      ansible.builtin.set_fact:
        deployment_firstrun_meta:
          - ResourceType: "auto-scaling-group"
            ResourceId: "{{ ec2_autoscaling_group }}"
            PropagateAtLaunch: true
            Key: "atl:deployment:commit-id"
            Value: "COMMIT: {{ git_out.stdout }}"

          - ResourceType: "auto-scaling-group"
            ResourceId: "{{ ec2_autoscaling_group }}"
            PropagateAtLaunch: true
            Key: "atl:deployment:first-run-timestamp"
            Value: "TIMESTAMP: {{ ansible_date_time.iso8601 }}"


    # Set the tags on the ASG and the local instance. We need to
    # ignore errors as it's possible we don't have the permissions,
    # and we can't check up-front.
    - name: Set the first-run tags on the ASG ("FAIL" is not critical)  # noqa: no-changed-when
      ansible.builtin.command: "aws autoscaling
                    create-or-update-tags
                    --region {{ ansible_ec2_placement_region }}
                    --tags '{{ deployment_firstrun_meta | to_json }}'"
      ignore_errors: true

    - name: Set the tags on the local instance ("FAIL" is not critical)
      amazon.aws.ec2_tag:
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
        tags:
          "atl:deployment:commit-id": "COMMIT: {{ git_out.stdout }}"
          "atl:deployment:first-run-timestamp": "TIMESTAMP: {{ ansible_date_time.iso8601 }}"
      ignore_errors: true

  when:
    - ec2_autoscaling_group != ''
    - ec2_instance_tags.tags['atl:deployment:first-run-timestamp'] is not defined
