---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "bitbucket"
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"

    atl_aws_iam_role: "atl_aws_iam_role"
    atl_aws_stack_name: "atl_aws_stack_name"
    atl_nfs_disk_volume_iops: "atl_nfs_disk_volume_iops"
    atl_nfs_disk_volume_type: "atl_nfs_disk_volume_type"
    atl_nfs_fs_type: "atl_nfs_fs_type"
    atl_proxy_name: "atl_proxy_name"
    atl_rds_instance_class: "atl_rds_instance_class"
    atl_rds_instance_id: "atl_rds_instance_id"
    atl_rds_multi_az: "atl_rds_multi_az"
    atl_rds_security_group: "atl_rds_security_group"
    atl_rds_subnet_group_name: "atl_rds_subnet_group_name"

  pre_tasks:
    - name: Create base dir
      ansible.builtin.file:
        path: '/opt/atlassian/bin'
        state: directory

    - name: Install git
      ansible.builtin.package:
        name: git

  roles:
    - role: diy_backup
