---

- name: Create mountpoint
  ansible.builtin.file:
    state: directory
    path: "{{ atl_shared_mountpoint }}"
    mode: 0755
    owner: "{{ atl_product_user }}"
    group: "{{ atl_product_user }}"

- name: Enable mountpoint in fstab
  ansible.posix.mount:
    src: "{{ atl_fileserver_host }}:{{ atl_nfs_target }}"
    path: "{{ atl_nfs_mountpoint }}"
    fstype: nfs
    opts: "rw,nfsvers={{ atl_nfs_version }},lookupcache=pos,noatime,intr,rsize=32768,wsize=32768,_netdev"
    state: mounted
  register: mount_result
  until: not mount_result.failed
  retries: 60
  delay: 5
